[8.0][hr_worked_days_compute_holiday] Adding new module hr_worked_days_compute_holiday
open-synergy/opnsynid-hr pull request #16
Opened 2017-02-07 04:34 UTC by mikevhe18

2017-02-07 08:48 UTC, andhit-r requested changes
Mike,

1. Pembuatan payslip melalui menu **Employee Payslips** berhasil. Perhitungannya ok.
2. Pembuatan payslip melalui menu **Payslip Batches** ada error. Video ada di https://youtu.be/coer4Xo3jrU

2017-02-08 04:25 UTC, andhit-r requested changes
@mikevhe18 masih ada yang salah. video di: https://youtu.be/xGwB3jjAnwY

2017-02-08 08:13 UTC, mikevhe18 commented
@andhit-r Mas, untuk validasi countrynya yang dilihat bukan dari home address mas, tetapi berdasarkan country di working address. Kalau misalnya contoh home address di Singapure, working addressnya di Indonesia, bearti seharusnya public holiday yang diitung khan yang di Indonesia

2017-02-08 08:17 UTC, andhit-r commented
Hoo oke cek dengan working address klo gitu

2017-02-09 09:17 UTC, andhit-r commented
@mikevhe18 msh salah mike. Video: https://youtu.be/hBqABRDbUnU

2017-02-10 04:56 UTC, andhit-r approved these changes

2017-02-10 04:56 UTC, merged