[8.0.1.0.0][hr_timesheet_auto_input] T0040
open-synergy/opnsynid-hr pull request #213
Opened 2020-04-22 02:41 UTC by mikevhe18

2020-04-29 15:19 UTC, andhit-r requested changes

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/views/hr_timesheet_sheet_view.xml
> +                    <div>
Biasakan untuk memberikan attribute _name_ pada element _group_ ataupun _div_

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +            return {"domain": {"task_id": [("id", "in", task_id)]}}
```suggestion
    @api.multi
    @api.onchange(
        "timesheet_account_id",
    )
    def onchange_task_id(self):
        self.task_id = False
```

Onchangenya cukup itu aja mike. Domainnya nanti tinggal dikontrol dari domain di view

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +            obj_hr_timesheet_sheet.search(criteria)
Ini lo cukup buat field sheet_id di wizardnya. Kemudian buat method defaultnya

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.xml
> +            </group>
Berikan attribute name untuk elemen group

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +    def create_analytic_timesheet(self, sheet_ids):
Param sheet_ids tidak diperlukan jika field sheet_id ditambahkan di wizard

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +    def _prepare_analytic_timesheet_data(self, sheet_ids):
Param sheet_ids tidak diperlukan jika field sheet_id ditambahkan di wizard

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        account_id =\
Jika tidak ada conditional nilai ini bisa langsung diberikan di return

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        task_id =\
Jika tidak ada conditional nilai ini bisa langsung diberikan di return

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        product_id =\
Jika tidak ada conditional nilai ini bisa langsung diberikan di return

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        journal_id =\
Jika tidak ada conditional nilai ini bisa langsung diberikan di return

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        difference =\
Jika tidak ada conditional nilai ini bisa langsung diberikan di return

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        domain=[("type", "<>", "view")],
Tidak perlu domain. Gunakan strategi allowed_timesheet_account_ids.

2020-04-29 15:19 UTC, andhit-r commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        domain=[("type", "=", "service")],
Tidak perlu domain. Gunakan allowed_product_categ_ids atau allowed_product_ids dari modul hr_timesheet_product_policy

2020-04-30 01:18 UTC, mikevhe18 commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        account_id =\
@andhit-r nilai ini sudah dibuat required dari awal, jadi pasti ga mungkin ga ada isinya mas

2020-04-30 01:19 UTC, mikevhe18 commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        product_id =\
@andhit-r nilai ini sudah dibuat required dari awal, jadi pasti ga mungkin ga ada isinya mas

2020-04-30 01:20 UTC, mikevhe18 commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        journal_id =\
@andhit-r nilai ini tergatung dari sheet employee_id dimana isinya tidak mungkin kosong, jadi pasti ga mungkin ga ada isinya mas

2020-04-30 01:27 UTC, mikevhe18 commented on hr_timesheet_auto_input/wizards/wizard_timesheet_auto_input.py
> +        domain=[("type", "<>", "view")],
@andhit-r kalau menggunakan strategi allowed_timesheet_account_ids, berarti untuk pengisian manual di timesheet pun harus dibuat allowednya, domain disini gw samakan sama domain awal form timesheet biar ga ada perbedaan

2020-11-10 10:49 UTC, closed without merging